name: Ejecucion de prueba local Mio

on:
  push:
    branches: [ "main" ]  # Se activar치 cada vez que subas algo a la rama main
  workflow_dispatch:      # Esto permite darle al bot칩n "Run workflow" manualmente

jobs:
  ejecutar-en-mi-pc:
    runs-on: self-hosted  # <--- Obligatorio para usar tu runner local

    steps:
      # Paso 1: Descargar el c칩digo del repo a la carpeta del runner
      - name: Checkout del c칩digo
        uses: actions/checkout@v4

      # Paso 2: Ejecutar tu script de Python
      - name: Ejecutar script prueba.py
        run: |
          python prueba.py
