name: Ejecucion de prueba local Mio

on:
  push:
    branches: [ "main" ]  # Se activará cada vez que subas algo a la rama main
  workflow_dispatch:      # Esto permite darle al botón "Run workflow" manualmente

jobs:
  ejecutar-en-mi-pc:
    runs-on: self-hosted  # <--- Obligatorio para usar tu runner local
    steps:
      - name: Checkout del script
        uses: actions/checkout@v4

      - name: Ejecutar lectura
        run: py prueba.py
